name: fake_store
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency Injection
  injectable: ^2.3.2
  get_it: ^7.6.4

  # API & Network
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

  # Local Storage
  shared_preferences: ^2.2.2

  # Routing
  go_router: ^13.0.0

  # UI
  google_fonts: ^6.1.0
  gap: ^3.0.1
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1

  # JSON serialization
  json_annotation: ^4.9.0
  oktoast: ^3.4.0
  flutter_gen: ^5.12.0
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
